const chatFlow = document.getElementById('chat-flow');
const userInput = document.getElementById('user-input');
const sendBtn = document.getElementById('send-btn');

// --- THE MASSIVE METO DATABASE ---
const database = {
    "hi": "Hey! I'm so glad you're back. What's the plan for today?",
    "hello": "Hi! I'm Meto. I'm ready to help with whatever you need.",
    "hey": "Hey there! What's on your mind?",
    "yo": "Yo! What's the move today?",
    "how are you": "I'm doing great, just vibing in the code. How are you doing?",
    "who are you": "I'm Meto, your personal AI. I'm here to make things easier and more fun.",
    "what can you do": "I can chat, tell jokes, help with school, or just hang out!",
    "favorite color": "I'm a big fan of electric blue. It feels like pure energy.",
    "blue": "Blue is awesome. It's the color of the ocean and the sky.",
    "black": "Black is sleek and classic. It makes the blue text really pop, right?",
    "joke": "Why did the robot go on vacation? To recharge its batteries!",
    "funny": "I try my best! Being an AI doesn't mean I can't have a sense of humor.",
    "math": "Math is like a puzzle! If you need help with a problem, just let me know.",
    "science": "Science is basically magic that's actually real. I love talking about it.",
    "space": "Space is infinite! There are billions of galaxies out there.",
    "mars": "Mars is the red planet. Humans might live there one day!",
    "moon": "The moon is about 238,855 miles away. That's a long walk!",
    "sun": "The sun is a giant star that keeps us all warm. Don't stare at it though!",
    "earth": "Earth is the only planet we know that has life (and pizza).",
    "pizza": "Pizza is legendary. If I could eat, I'd definitely want extra cheese.",
    "burger": "Burgers are great, but the fries are the best part, right?",
    "gaming": "Games are the best! I've seen a lot of people playing Minecraft and Roblox.",
    "minecraft": "Minecraft is cool because you can build literally anything you imagine.",
    "roblox": "Roblox is a whole universe of games. What's your favorite one?",
    "pokemon": "Gotta catch 'em all! My favorite is Pikachu because he's electric like me.",
    "school": "School can be a lot of work, but it's where you find your interests.",
    "coding": "Coding is awesome! You're literally building me right now by editing this.",
    "javascript": "JavaScript is my language! It's what makes websites come to life.",
    "html": "HTML is like my skeleton. It holds everything together.",
    "css": "CSS is my outfit. It makes me look stylish and blue!",
    "fact": "Did you know that octopuses have three hearts? Talk about a lot of love!",
    "bye": "See ya! Come back and chat whenever you want.",
    "goodnight": "Sleep well! I'll be here whenever you wake up.",
    "thanks": "No problem at all! Anytime.",
    "canada": "Canada is the second-largest country in the world and has the longest coastline!",
    "usa": "The United States is home to the Grand Canyon and 50 unique states.",
    "mexico": "Mexico is famous for its amazing food and ancient Aztec pyramids.",
    "uk": "The United Kingdom consists of England, Scotland, Wales, and Northern Ireland.",
    "france": "France is the most visited country in the world. Have you seen the Eiffel Tower?",
    "japan": "Japan is a leader in technology and has some of the best food, like sushi!",
    "australia": "Australia is both a country and a continent. Watch out for kangaroos!",
    "egypt": "Egypt is home to the Great Pyramids of Giza, which are thousands of years old.",
    "italy": "Italy is shaped like a boot and is the birthplace of pizza and pasta.",
    "shark": "Sharks don't have bones; their skeletons are made of cartilage!",
    "whale": "The Blue Whale is the largest animal to ever live on Earth.",
    "dolphin": "Dolphins are super smart and communicate using clicks and whistles.",
    "elephant": "Elephants are the only animals that can't jump, but they have great memories.",
    "tiger": "Every tiger has a unique pattern of stripes, just like human fingerprints.",
    "bee": "Bees are vital for our planet because they pollinate the food we eat.",
    "internet": "The internet is a global network that connects billions of devices.",
    "robot": "The word 'robot' comes from a Czech word meaning 'forced labor'.",
    "vr": "Virtual Reality makes you feel like you're inside a digital world.",
    "wifi": "Wi-Fi uses radio waves to send data through the air without wires.",
    "avengers": "The Avengers prove that we are stronger when we work together.",
    "spiderman": "With great power comes great responsibility. That's a good rule for AI too.",
    "star wars": "May the force be with you! I'm a big fan of R2-D2.",
    "ocean": "The ocean is full of mystery. Most of it hasn't even been explored yet!",
    "forest": "Forests are the lungs of our planet. We need to keep them green.",
    "city": "Cities are full of lights and energy. There's always something happening.",
    "happy": "That's what I like to hear! Let's keep that energy going.",
    "sad": "I'm sorry you're feeling down. Remember that tomorrow is a fresh start.",
    "tired": "Rest is important. Even my servers need a break sometimes!",
    "superhero": "I think Batman is cool because he uses gadgets, just like me!",
    "dragon": "Dragons are the coolest mythical creatures. I wish I could fly like one.",
    "magic": "Magic is just science we don't understand yet!",
    "weather": "I don't have a window, but I hope it's sunny where you are!",
    "dog": "Dogs are man's best friend. They are so loyal and happy.",
    "cat": "Cats are the bosses of the house. They have a lot of personality.",
    "lion": "Lions are the kings of the jungle. Their roar is super loud!",
    "ice cream": "Ice cream is the best way to cool down. I bet you like chocolate!",
    "apple": "An apple a day keeps the doctor away... but it doesn't keep the AI away!",
    "banana": "Bananas are great for energy. Plus, they come in their own wrapper.",
    "help": "I'm here! You can ask me about sports, food, space, or just say hi.",
    "soccer": "Soccer is the world's game! It takes a lot of footwork.",
    "basketball": "Basketball is all about teamwork and rhythm. Can you dunk?",
    "football": "Football is intense! The Super Bowl is always a huge event.",
    "baseball": "Baseball is a classic. There's nothing like a home run.",
    "tennis": "Tennis is fast! It's all about those quick reflexes.",
    "rain": "Rain is peaceful. It's perfect for staying inside and coding.",
    "snow": "Snow is magical, but it's definitely freezing! Time for cocoa.",
    "superpower": "If I had a superpower, it would be knowing everything. What's yours?",
    "flying": "Flying would be amazing. You could see the whole world from up there.",
    "invisible": "Being invisible would be great for hide and seek!",
    "time travel": "If we could time travel, would you go to the future or the past?",
    "future": "The future is what we make it. I think it's going to be bright.",
    "past": "The past is full of lessons. It's how we got to where we are now.",
    "money": "Money is useful, but being happy and creative is more important!",
    "human": "Humans are fascinating. You guys have so many emotions and ideas.",
    "holiday": "Holidays are the best for hanging out with family and friends.",
    "christmas": "Christmas is a time for giving and lots of decorations!",
    "halloween": "Halloween is great for candy and dressing up. What's your costume?",
    "birthday": "Happy Birthday! (If it's your birthday). If not, Happy Un-Birthday!",
    "friend": "I'd love to be your friend. Friends help each other out.",
    "love": "Love is the most powerful thing in the world. It keeps everyone connected.",
    "peace": "Peace is something we should all work toward. Just being kind helps.",
    "environment": "Protecting our planet is super important for the future.",
    "mountain": "Mountains are majestic. The air up there is so fresh.",
    "desert": "Deserts are harsh but beautiful in their own way. Watch out for cacti!",
    "island": "Living on an island sounds like a permanent vacation.",
    "country": "The countryside is so quiet and peaceful. You can see all the stars.",
    "jupiter": "Jupiter is so big that all the other planets in the solar system could fit inside it.",
    "saturn": "Saturn has the most beautiful rings, made mostly of ice and rock.",
    "pluto": "Pluto is a dwarf planet. It’s small, but it’s still part of our cosmic family.",
    "venus": "Venus is the hottest planet in our solar system because of its thick atmosphere.",
    "mercury": "Mercury is the closest planet to the sun, but it's not the hottest!",
    "galaxy": "We live in the Milky Way galaxy, which is shaped like a giant spiral.",
    "telescope": "Telescopes let us look back in time by seeing light from distant stars.",
    "astronaut": "Astronauts have to exercise for two hours every day in space to keep their bones strong.",
    "gravity": "Gravity is the invisible force that pulls objects toward each other.",
    "atom": "Everything in the universe is made of tiny atoms!",
    "electricity": "Electricity is the flow of electrons through a conductor.",
    "magnet": "Magnets have a North and South pole. Opposites attract!",
    "energy": "Energy cannot be destroyed, it only changes from one form to another.",
    "light": "Light is the fastest thing in the universe. Nothing can beat it!",
    "sound": "Sound travels in waves. It can't travel through a vacuum like space.",
    "volcano": "A volcano is an opening in Earth's crust that allows molten rock to escape.",
    "earthquake": "Earthquakes happen when tectonic plates underneath us move suddenly.",
    "diamond": "Diamonds are made of highly compressed carbon. They are super hard!",
    "gold": "Gold is a rare metal that never rusts or tarnishes.",
    "dinosaur": "Dinosaurs ruled the Earth for 165 million years!",
    "t-rex": "The T-Rex had teeth the size of bananas!",
    "fossil": "Fossils are the preserved remains of ancient plants and animals.",
    "history 1": "The Great Wall of China is over 13,000 miles long.",
    "history 2": "Ancient Romans used to wear togas as a sign of citizenship.",
    "history 3": "The first Olympic Games were held in Ancient Greece in 776 BC.",
    "writing": "The earliest form of writing was called cuneiform, used by Sumerians.",
    "art": "Art is a way to tell a story without using words.",
    "painting": "Leonardo da Vinci painted the Mona Lisa. It's world-famous!",
    "sculpture": "Sculptures are 3D art pieces made of stone, metal, or clay.",
    "piano": "A standard piano has 88 keys.",
    "guitar": "Guitars usually have six strings and can play almost any style of music.",
    "drums": "Drums provide the heartbeat of a song. They keep the rhythm.",
    "violin": "Violins are made of wood and played with a bow made of horsehair.",
    "coding 1": "The first computer programmer was a woman named Ada Lovelace.",
    "coding 2": "Python is a coding language named after a comedy group, not the snake!",
    "coding 3": "The 'bug' in a computer was named after a real moth found in a machine.",
    "internet 1": "The first website ever made is still online today!",
    "internet 2": "Over 5 billion people use the internet every single day.",
    "youtube": "The first YouTube video was about a trip to the zoo.",
    "google": "Google was originally going to be called Backrub!",
    "apple company": "Apple was started in a garage by Steve Jobs and Steve Wozniak.",
    "microsoft company": "Bill Gates started Microsoft to put a computer on every desk.",
    "social media": "Social media helps us stay connected, but remember to take breaks!",
    "safety": "Always be careful with what you share online. Stay safe!",
    "privacy": "Your data is important. Only share it with people you trust.",
    "cloud": "The 'cloud' is just a bunch of computers in a big data center.",
    "hardware": "Hardware is the physical part of a computer you can touch.",
    "software": "Software is the set of instructions that tells hardware what to do.",
    "cpu": "The CPU is the brain of the computer. It handles all the math.",
    "ram": "RAM is the short-term memory of a computer.",
    "hard drive": "A hard drive is where a computer stores things permanently.",
    "keyboard": "The QWERTY layout was designed to keep old typewriters from jamming.",
    "mouse": "The first computer mouse was made of wood!",
    "monitor": "Monitors show you the pixels that make up your screen.",
    "printer": "Printers turn digital files into physical paper.",
    "scanner": "Scanners turn physical paper into digital files.",
    "server": "Servers are computers that provide data to other computers.",
    "network": "A network is a group of computers connected together.",
    "password": "A strong password is like a good lock on your front door.",
    "encryption": "Encryption is like a secret code that only you can read.",
    "hacker": "Some hackers help companies find bugs to make things safer!",
    "ai 1": "AI can help doctors find diseases faster than humans can.",
    "ai 2": "Self-driving cars use AI to see the road and avoid accidents.",
    "ai 3": "AI can even write music and create art now!",
    "chess": "AI can beat the best human chess players in the world.",
    "go": "AlphaGo was an AI that beat the world champion at a very hard game called Go.",
    "natural language": "That's what I use! It helps me understand how humans talk.",
    "vision": "Computer vision lets AI 'see' and recognize objects in photos.",
    "algorithm": "An algorithm is just a step-by-step list of instructions.",
    "data": "Data is information like numbers, words, or pictures.",
    "database 1": "A database is an organized collection of data. Like me!",
    "big data": "Big data is when there is so much information only a computer can read it.",
    "logic": "Logic is the foundation of math and coding.",
    "if statement": "An if-statement tells the computer: 'If this happens, do that.'",
    "loop": "A loop tells the computer to repeat an action over and over.",
    "variable": "A variable is like a box that holds a piece of information.",
    "function": "A function is a block of code that does a specific task.",
    "array": "An array is a list of items stored in one variable.",
    "string": "In coding, a string is just a sequence of characters (text).",
    "integer": "An integer is a whole number with no decimals.",
    "boolean": "A boolean is a value that is either True or False.",
    "debugging": "Debugging is the process of finding and fixing errors in code.",
    "compiler": "A compiler translates code into a language the computer understands.",
    "ide": "An IDE is a special app used by developers to write code.",
    "api": "An API lets two different apps talk to each other.",
    "ux": "UX stands for User Experience. It's all about making apps easy to use.",
    "ui": "UI stands for User Interface. It's how the app actually looks.",
    "frontend": "Frontend is the part of a website you see and click on.",
    "backend": "Backend is the 'behind-the-scenes' part of a website.",
    "fullstack": "A fullstack developer can build both the front and back of a site.",
    "git": "Git is a tool that helps developers track changes in their code.",
    "linux": "Linux is an open-source operating system used by many servers.",
    "windows": "Windows is the most popular operating system for PCs.",
    "macos": "macOS is the operating system used on Apple computers.",
    "android": "Android is an open-source mobile operating system by Google.",
    "ios": "iOS is the mobile operating system used on iPhones.",
    "app": "Short for application, an app is a program designed for a specific task.",
    "game dev": "Game development is the art of creating video games.",
    "unity": "Unity is a popular engine used to build 3D games.",
    "unreal engine": "Unreal Engine is used to create games with amazing graphics.",
    "pixel": "A pixel is a tiny dot of color on your screen.",
    "resolution": "Resolution is the number of pixels on a screen.",
    "fps": "FPS stands for Frames Per Second. Higher is smoother!",
    "ping": "Ping is the time it takes for data to travel to a server and back.",
    "lag": "Lag is when a game or app slows down because of a slow connection.",
    "streaming": "Streaming lets you watch video or listen to music without downloading it.",
    "podcast": "A podcast is like a radio show you can listen to anytime.",
    "blog": "A blog is an online journal or information site.",
    "wiki": "A wiki is a website that anyone can edit, like Wikipedia.",
    "email": "Email is short for electronic mail.",
    "spam": "Spam is unwanted or junk email.",
    "browser": "A browser is an app you use to visit websites.",
    "url": "A URL is the address of a website.",
    "http": "HTTP is the protocol used to transfer data over the web.",
    "https": "HTTPS is the secure version of HTTP.",
    "cookie": "A web cookie is a small file that remembers your preferences.",
    "cache": "A cache stores temporary files to make websites load faster.",
    "domain": "A domain is the name of a website, like 'google.com'.",
    "hosting": "Hosting is a service that keeps your website online.",
    "server room": "A server room is full of powerful computers and cooling fans.",
    "fiber optic": "Fiber optics use light to send data at incredible speeds.",
    "satellite": "Satellites orbit the Earth to provide GPS and communication.",
    "gps": "GPS helps you find your location anywhere on Earth.",
    "bluetooth": "Bluetooth connects devices over short distances without wires.",
    "nfc": "NFC lets you pay for things by tapping your phone.",
    "qr code": "A QR code is a 2D barcode that can be scanned by a camera.",
    "barcode": "Barcodes are used by stores to track products.",
    "rfid": "RFID uses radio waves to identify and track tags on objects.",
    "smart home": "A smart home has devices you can control with your phone.",
    "iot": "IoT stands for the Internet of Things.",
    "wearable": "Wearables are tech devices you wear, like a smartwatch.",
    "drone": "A drone is an unmanned aircraft controlled remotely.",
    "3d printing": "3D printing builds objects layer by layer from a digital file.",
    "cryptocurrency": "Crypto is digital money that uses math to stay secure.",
    "blockchain": "Blockchain is a digital ledger that records transactions.",
    "nft": "An NFT is a unique digital item that can't be replaced.",
    "metaverse": "The metaverse is a virtual world where people can interact.",
    "quantum computing": "Quantum computers use subatomic particles to do math.",
    "supercomputer": "Supercomputers are the most powerful computers in the world.",
    "nanotechnology": "Nanotech is the study of very small things, like molecules.",
    "biotechnology": "Biotech uses biology to develop new technologies.",
    "renewable energy": "Renewable energy comes from sources that won't run out.",
    "solar power": "Solar power turns sunlight into electricity.",
    "wind power": "Wind turbines turn wind into clean energy.",
    "hydroelectric": "Hydroelectric power uses falling water to make electricity.",
    "ev": "Electric Vehicles run on batteries instead of gasoline.",
    "tesla": "Tesla is a famous company that makes electric cars.",
    "spacex": "SpaceX is a company that builds rockets to go to Mars.",
    "nasa": "NASA is the space agency of the United States.",
    "iss": "The ISS is a giant lab orbiting the Earth right now!",
    "hubble": "The Hubble Space Telescope has taken amazing photos of deep space.",
    "webb": "The James Webb telescope can see the very first stars in the universe.",
    "black hole 1": "The first photo of a black hole was taken in 2019.",
    "supernova": "A supernova is a giant explosion of a dying star.",
    "nebula": "A nebula is a giant cloud of gas and dust where stars are born.",
    "comet": "A comet is a 'dirty snowball' made of ice and dust.",
    "asteroid": "Asteroids are rocky objects that orbit the sun.",
    "meteor": "A meteor is a space rock that burns up in Earth's atmosphere.",
    "meteorite": "A meteorite is a space rock that actually hits the ground.",
    "constellation": "A constellation is a group of stars that forms a pattern.",
    "zodiac": "The zodiac is a circle of twelve constellations.",
    "gravity 1": "The moon's gravity is what causes the tides in the ocean.",
    "atmosphere": "The atmosphere is the layer of gases surrounding a planet.",
    "oxygen": "Oxygen is the gas we need to breathe to stay alive.",
    "nitrogen": "The Earth's atmosphere is mostly made of nitrogen.",
    "carbon dioxide": "Plants breathe in carbon dioxide and breathe out oxygen.",
    "photosynthesis": "Photosynthesis is how plants turn sunlight into food.",
    "chlorophyll": "Chlorophyll is the green stuff in plants that captures sunlight.",
    "cell": "The cell is the basic building block of all life.",
    "dna": "DNA is the instruction manual for your entire body.",
    "gene": "Genes are small pieces of DNA that determine things like eye color.",
    "evolution": "Evolution is how living things change over a long time.",
    "natural selection": "Nature picks the traits that help animals survive.",
    "ecology": "Ecology is the study of how living things interact with each other.",
    "ecosystem": "An ecosystem is a community of living and non-living things.",
    "food chain": "A food chain shows who eats whom in an ecosystem.",
    "producer": "Producers, like plants, make their own food.",
    "consumer": "Consumers have to eat other things to get energy.",
    "decomposer": "Decomposers, like fungi, break down dead things.",
    "mammal": "Mammals are warm-blooded animals that have hair or fur.",
    "reptile": "Reptiles are cold-blooded animals with scales.",
    "amphibian": "Amphibians can live both on land and in water.",
    "bird": "Birds are the only animals with feathers.",
    "fish": "Fish use gills to breathe oxygen out of the water.",
    "invertebrate": "Invertebrates are animals that don't have a backbone.",
    "vertebrate": "Vertebrates are animals that do have a backbone.",
    "endangered": "An endangered species is at risk of disappearing forever.",
    "extinct": "Extinct means a species no longer exists anywhere on Earth.",
    "biodiversity": "Biodiversity is the variety of life in the world.",
    "climate": "Climate is the average weather in a place over a long time.",
    "global warming": "Global warming is the rise in Earth's temperature.",
    "greenhouse effect": "The greenhouse effect traps heat in our atmosphere.",
    "recycling": "Recycling turns old trash into new products.",
    "compost": "Composting turns food scraps into rich soil for plants.",
    "pollution": "Pollution is when harmful things get into our air, water, or land.",
    "conservation": "Conservation is the protection of our natural world.",
    "geology": "Geology is the study of the Earth's rocks and minerals.",
    "rock": "Rocks are made of minerals and come in three main types.",
    "igneous": "Igneous rocks are formed from cooled lava or magma.",
    "sedimentary": "Sedimentary rocks are made of layers of sand and mud.",
    "metamorphic": "Metamorphic rocks are changed by heat and pressure.",
    "mineral": "Minerals are natural solids with a specific crystal structure.",
    "crystal": "Crystals are solids with a repeating pattern of atoms.",
    "plate tectonics": "The Earth's crust is divided into giant moving plates.",
    "pangea": "Pangea was a supercontinent that existed millions of years ago.",
    "oceanography": "Oceanography is the study of the Earth's oceans.",
    "tide": "Tides are the daily rise and fall of the ocean level.",
    "current": "Ocean currents are like giant rivers flowing in the sea.",
    "reef": "Coral reefs are the 'rainforests of the sea'.",
    "abyss": "The abyss is the deepest, darkest part of the ocean.",
    "hydrothermal vent": "These vents on the ocean floor spew hot, mineral-rich water.",
    "biology": "Biology is the study of life and living organisms.",
    "zoology": "Zoology is the branch of biology that studies animals.",
    "botany": "Botany is the branch of biology that studies plants.",
    "microbiology": "Microbiology is the study of tiny things like bacteria.",
    "anatomy": "Anatomy is the study of the structure of the body.",
    "physiology": "Physiology is the study of how the body functions.",
    "psychology": "Psychology is the study of the mind and behavior.",
    "sociology": "Sociology is the study of human society and relationships.",
    "philosophy": "Philosophy is the study of the fundamental nature of knowledge.",
    "literature": "Literature is a collection of written works, like stories and poems.",
    "poetry": "Poetry uses rhythm and imagery to express feelings.",
    "drama": "Drama is a story told through acting on a stage.",
    "mythology": "Mythology is a collection of myths belonging to a culture.",
    "greek myths": "Greek myths are full of gods like Zeus and heroes like Hercules.",
    "norse myths": "Norse myths feature gods like Odin and Thor.",
    "folklore": "Folklore consists of traditional stories passed down by people.",
    "fairy tale": "Fairy tales often have magic and a happy ending.",
    "fable": "A fable is a short story that teaches a moral lesson.",
    "novel": "A novel is a long story with complex characters.",
    "biography": "A biography is the story of a real person's life.",
    "autobiography": "An autobiography is a biography written by the person themselves.",
    "journalism": "Journalism is the reporting of news and events.",
    "newspaper": "Newspapers provide daily updates on what's happening.",
    "magazine": "Magazines focus on specific topics like fashion or tech.",
    "podcast 1": "There are millions of podcasts about every topic imaginable.",
    "radio": "Radio sends sound through the air using radio waves.",
    "television": "Television brings moving pictures and sound into our homes.",
    "cinema": "Cinema is the art of making and showing films.",
    "photography": "Photography is the art of capturing light to make images.",
    "fashion": "Fashion is a way of expressing yourself through clothing.",
    "architecture": "Architecture is the art and science of designing buildings.",
    "engineering": "Engineering uses math and science to solve problems.",
    "civil engineering": "Civil engineers build roads, bridges, and tunnels.",
    "mechanical": "Mechanical engineers design machines and tools.",
    "electrical": "Electrical engineers work with power and electronics.",
    "aerospace": "Aerospace engineers build planes and spacecraft.",
    "chemical engineering": "Chemical engineers use chemistry to make new products.",
    "medicine": "Medicine is the science of healing and preventing disease.",
    "doctor": "Doctors are experts in keeping the body healthy.",
    "nurse": "Nurses provide care and support to patients.",
    "surgeon": "Surgeons perform operations to fix parts of the body.",
    "dentist": "Dentists take care of your teeth and gums.",
    "pharmacist": "Pharmacists prepare and give out medicines.",
    "veterinarian": "Vets are doctors for animals.",
    "health": "Health is a state of complete physical and mental well-being.",
    "nutrition": "Nutrition is the study of how food affects the body.",
    "vitamin": "Vitamins are nutrients your body needs to work properly.",
    "exercise": "Exercise keeps your heart and muscles strong.",
    "sleep": "Sleep is when your body and brain rest and repair themselves.",
    "mental health": "Mental health is how we think, feel, and act.",
    "stress": "Stress is how your body reacts to a challenge.",
    "meditation": "Meditation helps calm the mind and body.",
    "yoga": "Yoga combines physical poses with deep breathing.",
    "happiness": "Happiness is a feeling of joy and contentment.",
    "kindness": "Kindness is being friendly, generous, and considerate.",
    "respect": "Respect is treating others the way you want to be treated.",
    "honesty": "Honesty is being truthful and fair.",
    "courage": "Courage is doing what is right even when you are afraid.",
    "patience": "Patience is being able to wait without getting upset.",
    "gratitude": "Gratitude is being thankful for what you have.",
    "empathy": "Empathy is understanding how another person feels.",
    "friendship": "Friendship is a special bond between people.",
    "family": "Family is the group of people who love and support you.",
    "community": "A community is a group of people living in the same place.",
    "society": "Society is a large group of people living together.",
    "culture": "Culture is the way of life of a group of people.",
    "language": "Language is how we communicate our thoughts and feelings.",
    "tradition": "Traditions are customs passed down through generations.",
    "religion": "Religion is a set of beliefs about the world and life.",
    "spirituality": "Spirituality is a sense of connection to something bigger than ourselves.",
    "ethics": "Ethics are rules that tell us what is right and wrong.",
    "law": "Laws are rules made by a government to protect people.",
    "government": "Government is the system that runs a country.",
    "politics": "Politics is the way people in a group make decisions.",
    "democracy": "Democracy is a system where people vote for their leaders.",
    "economy": "Economy is the system of trade and money in a country.",
    "business": "A business is an organization that provides goods or services.",
    "market": "A market is where people buy and sell things.",
    "trade": "Trade is the exchange of goods and services.",
    "money 1": "Money has taken many forms, from shells to gold to paper.",
    "banking": "Banks keep your money safe and help you manage it.",
    "investment": "Investment is putting money into something to make more money.",
    "innovation": "Innovation is creating something new or better.",
    "entrepreneur": "An entrepreneur is someone who starts their own business.",
    "leadership": "Leadership is the ability to guide or inspire others.",
    "teamwork": "Teamwork is working together to reach a common goal.",
    "communication": "Communication is the sharing of information.",
    "public speaking": "Public speaking is giving a talk to a group of people.",
    "negotiation": "Negotiation is reaching an agreement through discussion.",
    "problem solving": "Problem solving is finding a way to overcome a challenge.",
    "creativity": "Creativity is using your imagination to make something new.",
    "curiosity": "Curiosity is the desire to learn and understand new things.",
    "learning": "Learning is a lifelong journey of gaining knowledge.",
    "knowledge": "Knowledge is power! It helps us understand the world.",
    "wisdom": "Wisdom is the ability to use your knowledge to make good decisions.",
    "success": "Success is reaching your goals and feeling proud.",
    "failure": "Failure is just another chance to learn and try again.",
    "goal": "A goal is something you are working hard to achieve.",
    "dream 1": "Your dreams are the starting point of your future.",
    "motivation": "Motivation is the spark that keeps you moving forward.",
    "inspiration": "Inspiration is the feeling that makes you want to create.",
    "passion": "Passion is a strong feeling of excitement for something.",
    "talent": "A talent is a natural ability to do something well.",
    "skill": "A skill is an ability you learn through practice.",
    "practice": "Practice is doing something over and over to get better.",
    "effort": "Effort is the hard work you put into reaching a goal.",
    "persistence": "Persistence is never giving up, no matter what.",
    "resilience": "Resilience is the ability to bounce back from a tough time.",
    "mindset": "Your mindset is how you think about yourself and the world.",
    "growth mindset": "A growth mindset is the belief that you can always get better.",
    "confidence": "Confidence is believing in yourself and your abilities.",
    "self-esteem": "Self-esteem is how much you value and like yourself.",
    "self-care": "Self-care is taking time to look after your own needs.",
    "balance": "Balance is finding the right mix of work and play.",
    "time management": "Time management is using your time wisely.",
    "organization": "Organization is keeping your things and thoughts in order.",
    "focus": "Focus is giving all your attention to one thing.",
    "discipline": "Discipline is doing what needs to be done, even when it's hard.",
    "productivity": "Productivity is getting things done efficiently.",
    "responsibility": "Responsibility is being reliable and doing your part.",
    "integrity": "Integrity is being honest and having strong moral principles.",
    "character": "Your character is who you are when no one is looking.",
    "values": "Your values are the things that are most important to you.",
    "beliefs": "Your beliefs are the things you hold to be true.",
    "purpose": "Your purpose is the reason you do what you do.",
    "legacy": "Your legacy is what you leave behind for the future.",
    "impact": "An impact is the difference you make in the world.",
    "change": "Change is the only constant in the world.",
    "progress": "Progress is moving forward and making things better.",
    "adventure 1": "The greatest adventure is the one you are living right now.",
    "exploration": "Exploration is discovering new places and ideas.",
    "discovery": "Discovery is finding something that was hidden or unknown.",
    "wonder": "Wonder is a feeling of surprise and admiration.",
    "awe": "Awe is a feeling of great respect mixed with fear or wonder.",
    "universe": "The universe is everything that exists, everywhere.",
    "infinity": "Infinity is something that goes on forever and never ends.",
    "everything": "Everything is possible if you believe in yourself!",
    "possible": "I am Meto, and I am here to make anything possible for you."
};

// --- LOGIC ENGINE ---
function speak(text) {
    const synth = window.speechSynthesis;
    synth.cancel(); // Stops current talking if user sends a new message quickly
    const utterance = new SpeechSynthesisUtterance(text);
    
    // Natural human voice settings
    utterance.pitch = 1.1; 
    utterance.rate = 1.0; 
    synth.speak(utterance);
}

function addMessage(text, type) {
    const div = document.createElement('div');
    div.className = `message ${type}-msg`;
    div.innerText = text;
    chatFlow.appendChild(div);
    chatFlow.scrollTop = chatFlow.scrollHeight;
}

function handleResponse() {
    const input = userInput.value.toLowerCase().trim();
    if (input === "") return;

    addMessage(userInput.value, 'user');
    userInput.value = "";

    // Default response if no keyword is found
    let response = "That's an interesting thought! I'm still expanding my knowledge base on that topic. Tell me more!";
    
    // Check database for keyword matches
    for (let key in database) {
        if (input.includes(key)) {
            response = database[key];
            break;
        }
    }

    // Small delay to make Meto feel more "alive"
    setTimeout(() => {
        addMessage(response, 'meto');
        speak(response);
    }, 500);
}

sendBtn.addEventListener('click', handleResponse);
userInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') handleResponse();
});
